project:
  type: website

  render:
    - "*.qmd"

  resources: 
    - "files/**"

freeze: auto

website:
  title: "Sandstone Sonnets"
  favicon: "/poems/images/logo_circle.svg"
  site-url: "https://thomascwells.com/sandstonesonnets/"
  repo-url: "https://github.com/thomascwells/sandstonesonnets"
  repo-actions: [edit, issue]
  navbar:
    pinned: false
    logo: "/poems/images/logo_circle.svg"
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: rss
        href: index.xml
  margin-header: |
    ![](/poems/images/logo_circle.svg)
      
format:
  html:
    theme: 
      - lumen
      # - html/styles.scss
#    grid: 
#      body-width: 900px
    toc: false
#    highlight-style: monokai
    css: styles.css

  
  
  
