project:
  type: website

  render:
    - "*.qmd"

  resources: 
    - "files/**"

freeze: auto

website:
  title: "Sandstone Sonnets"
  favicon: "/poems/images/logo_circle.svg"
  site-url: "https://thomascwells.com/sandstonesonnets/"
  repo-url: "https://github.com/thomascwells/sandstonesonnets"
  repo-actions: [edit, issue]
  bread-crumbs: true
  navbar:
    pinned: false
    logo: "/poems/images/logo_circle.svg"
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      # - text: group1
      #   menu:
      #   - text: About the Author
      #     href: https://thomascwells.com
      #   - text: Source Code
      #     href: https://github.com/thomascwells/sandstonesonnets
      # - text: group 2
    right:
      - icon: rss
        href: index.xml
  margin-header: |
    ![](/poems/images/logo_circle.svg)
      
format:
  html:
    theme: 
      - lumen
      # - html/styles.scss
#    grid: 
#      body-width: 900px
    toc: false
#    highlight-style: monokai
    css: styles.css

  
  
  
