---
title: "FAQ"
---

### How do I use this website?

Use the "Trailhead filters" section on the homepage to find a trail near you. Select a trail to explore.  

The "Poems" section will now be filtered to just the trail selected.

Features on out-and-back trails are numbered sequentially, in the order they are found on the hike in. Features on loop trails are numbered in a clockwise fashion. If you're hiking counter-clockwise, you'll see them in reverse order.  

Each poem will give you clues about what shape to look for in the rocks. If you're stuck, there are hints at the bottom of the page under each poem. Clicking the hint will expand it.

Once you think you've found the rock formation described in the poem, click the "Answer" tab. It will show you a picture of the formation and a map showing the location where the picture was taken. GPS coordinates are included in the answer section to help you find the exact location.

### Why are you writing these poems?

As you've discovered by now, we aren't poets. We're just Fruita residents who are inspired by the unique rock formations and magical landscapes right in our backyard. These poems are a fun excuse to encourage exploration and share our appreciation of the Grand Valley.

### I think the rocks look like something different. How can I let you know?

[Email us!](mailto:mail@sandstonesonnets.com?subject=Poem%20Feedback&body=I%20think%20the%20poem%20about%20%5Binsert%20trailhead%20name%5D%20feature%20number%20%5Binsert%20feature%20number%5D%20should%20be%20changed%20because...) We love hearing from readers. If you have a suggestion for a different shape or interpretation, please let us know!

### Can I submit a poem to Sandstone Sonnets?

For sure! [Send us an email.](mailto:mail@sandstonesonnets.com?subject=Poem%20Submission&body=I%20would%20like%20to%20submit%20the%20following%20poem%20for%20consideration:%0A%0A%5Binsert%20poem%20text%20here%5D) Please include the trailhead and trail section you are writing about, as well as any hints you think would be helpful. We reserve the right to edit submissions for clarity, but you'll be credited for your poem.

### I don't want to write a poem, but I know a cool rock formation you should write one about. Can I submit that?

Of course! [Send it over!](mailto:mail@sandstonesonnets.com?subject=Poem%20Suggestion&body=I%20have%20a%20great%20idea%20for%20a%20poem%20about%20%5Binsert%20location%20here%5D.) We love hearing about new places to explore.

### I hate to tell you this, but these aren't sonnets.

I hate to tell you this, but that isn't a question. Nonetheless, your point is a good one -- these aren't sonnets. We liked the alliteration of Sandstone Sonnets more than we liked actual sonnets.