---
listing:
  contents: poems
  sort: "subtitle"
  sort-ui: true
  filter-ui: true
  type: default
  categories: unnumbered
  feed: true
  image-height: "0"
---

## What is this?

Welcome to Sandstone Sonnets! We're so glad you're here.  

On this page you'll find short, fun poems written about natural features (mostly rock formations) in and around Fruita, Colorado. These are a bit like a scavenger hunt. See if you can figure out what landscape features these poems describe.  

For more information about how to use the website, check out the [FAQ](/faq) page.  

Now it's time to pack your imagination and hit the trails! 

## Trailhead filters
*Selecting a location will filter the list of poems below.*

- [All](/)
- [Devil's Canyon](/#category=devil's%20canyon)
  - [D4](/#category=D4)
- [Flume Canyon](/#category=flume%20canyon)
  - [F1](/#category=F1)
- [Kodel's Canyon](/#category=kodel's%20canyon)
  - [K1](/#category=K1)
  - [K12](/#category=K12)
- [Colorado National Monument](/#category=national%20monument)
  - [Monument Canyon](/#category=monument%20canyon)
- [Rattlesnake Arches](/#category=rattlesnake%20arches)
  - [R1](/#category=R1)

## Poems
