---
title: "The Canyon's Secret Grin"
description: "Turn that frown upside down"
author: "Rudy"
date: "2025-09-14"
# date-modified: "2025-09-14"
draft: false
categories:
  - fruita
  - poems
  - devil's canyon
  - D4
---

If you search the canyon wall,  
A cheeky smile grins down at all.  
Red rock carved by wind and time,  
Sharing nature's favorite rhyme.

Green trees giggle from above,  
Junipers whisper tales of love.  
While hikers stop and point with glee:  
"Look! The canyon's smiling at me!"

This sandstone jester never frowns,  
Just grins at all the desert towns.  
A million-year-old happy face,  
That makes D4 such a lovely place!

So if you're walking Fruita's trails  
And need a laugh when courage fails,  
Just look up at that crimson wall—  
The canyon's smiling after all!  

::: {.panel-tabset}

## Hints

::: {.callout-tip collapse="true"}
## Hint #1: Umm...what am I looking for?

There is a place somewhere on the D4 trail where it looks like a big smile was carved into the sandstone.
:::

::: {.callout-tip collapse="true"}
## Hint #2: In what general area should I look?

This feature is located on the loop section of D4.
:::

::: {.callout-tip collapse="true"}
## Hint #3: Ok, I need a photo please.

INSERT IMAGE.
:::

## Answer

INSERT IMAGE  

```{python}
from ipyleaflet import Map, basemaps, basemap_to_tiles

lat = 39.156517
long = -108.710908

print("title=", f"Photo location: {39.156517}, {-108.710908}")

Map(basemap=basemap_to_tiles(basemaps.OpenStreetMap.Mapnik),
    center=(lat, long), zoom=1)
```

:::

